// import './example/basic-type.ts'
// import './example/symbol.ts'
// import './example/interface'
// import './example/function'
// import './example/generics'
// import './example/es6-class-1.js'
// import './example/es6-class-2.js'
// import './example/class'
// import './example/enum'
// import './example/interface-compatibility'
// import './example/interface-compatibility'
// import './example/advanced-type-1.ts'
// import './example/advanced-type-2.ts'
// import './modules/index.js'
// import './ts-modules/index'
// import './example/merging'
import './example/decorators'