// import './example/basic-type.ts'
// import './example/symbol.ts'
// import './example/interface'
// import './example/function'
// import './example/generics'
// import './example/es6-class-1.js'
// import './example/es6-class-2.js'
// import './example/class'
import './example/enum'